[package]
name = "geocoder-abbreviations"
version = "4.6.8"
license = "MIT"
description = "Geocoding Abbreviations classified by language and type"
authors = [
    "Mapbox <info@mapbox.com>",
    "Nick Ingalls <nick@ingalls.ca>"
]

edition = "2018"

[dependencies]
alphanumeric-sort = "1.0.6"
fancy-regex = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.rust-embed]
version = "5.5.1"
default-features = false
features = ["debug-embed"]
